//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LactoBioticsSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EFV0F9NE\\CEJASEARL;Initial Catalog=LactoBiotics;Integrated Sec" +
            "urity=True")]
        public string LactoBioticsConnectionString {
            get {
                return ((string)(this["LactoBioticsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EFV0F9NE\\CEJASEARL;Initial Catalog=LactoBioticsss;Integrated S" +
            "ecurity=True")]
        public string LactoBioticsssConnectionString {
            get {
                return ((string)(this["LactoBioticsssConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EFV0F9NE\\CEJASEARL;Initial Catalog=Lacto;Integrated Security=T" +
            "rue")]
        public string LactoConnectionString {
            get {
                return ((string)(this["LactoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EFV0F9NE\\CEJASEARL;Initial Catalog=LactoBioticss;Integrated Se" +
            "curity=True")]
        public string LactoBioticssConnectionString {
            get {
                return ((string)(this["LactoBioticssConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-EFV0F9NE\\cejasearl;Initial Catalog=LactoBiotics;Integrated Sec" +
            "urity=True")]
        public string LactoBioticsConnectionString1 {
            get {
                return ((string)(this["LactoBioticsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NEIL\\SQLEXPRESS;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=" +
            "True")]
        public string CJLSFOODSPAYROLLConnectionString {
            get {
                return ((string)(this["CJLSFOODSPAYROLLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NEIL\\SQLEXPRESS;Initial Catalog=LactoBioticsss;Integrated Security=Tr" +
            "ue")]
        public string LactoBioticsssConnectionString1 {
            get {
                return ((string)(this["LactoBioticsssConnectionString1"]));
            }
        }
    }
}
